version: '3.8'
services:
  guacamole:
    container_name: guacamole
    image: oznu/guacamole
    restart: unless-stopped
    volumes:
      - config:/config
    ports:
      - 8080
    networks:
      - npm
   
volumes:
  config:
  
networks:
  npm:
    external: true

