services:
  filebrowser:
    container_name: filebrowser
    image: filebrowser/filebrowser
    volumes:
      - /var/lib/docker/volumes/:/srv 
    networks:
      - npm

networks:
  npm:
    external: true
