
services:
  # guacd
  guacd:
    container_name: guacd
    image: guacamole/guacd
    networks:
      - npm
    restart: always
    volumes:
    - drive:/drive:rw
    - record:/record:rw

  # postgres
  postgres:
    container_name: guacamole_database
    environment:
      PGDATA: /var/lib/postgresql/data/guacamole
      POSTGRES_DB: guacamole_db
      POSTGRES_PASSWORD: 'ChooseYourOwnPasswordHere1234'
      POSTGRES_USER: 'guacamole_user'
    image: postgres:15.0
    networks:
      npm
    restart: always
    volumes:
    - ./init:/docker-entrypoint-initdb.d:ro
    - db:/var/lib/postgresql/data:rw

  # guacamole
  guacamole:
    container_name: guacamole
    depends_on:
    - guacd
    environment:
      GUACD_HOSTNAME: guacd
      POSTGRESQL_DATABASE: guacamole_db
      POSTGRESQL_HOSTNAME: postgres
      POSTGRESQL_PASSWORD: 'ChooseYourOwnPasswordHere1234'
      POSTGRESQL_USER: 'guacamole_user'
      POSTGRESQL_AUTO_CREATE_ACCOUNTS: true
    image: guacamole/guacamole
    networks:
      - npm
    volumes:
      - record:/record:rw
    ports:
      - 8080/tcp
    restart: always
  
  

   
volumes:
  drive:
  record:
  db:
  
networks:
  npm:
    external: true
