version: '3.8'
services:
  teleport:
    container_name: teleport
    image: public.ecr.aws/gravitational/teleport-distroless:16.2.0
    restart: unless-stopped
    volumes:
      - ./config:/etc/teleport 
      - data:/var/lib/teleport
    ports:
      - 3025:3025
      - 3080:3080
     
    networks:
      - npm
   
volumes:
  data:
  
networks:
  npm:
    external: true

